from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph
from datetime import datetime


def create_report(username, title, content):

    filename = f"{username}_report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>Cyber Security Report</b>", styles["Title"]))

    story.append(
        Paragraph(
            f"Generated By: {username}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Date: {datetime.now()}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/><br/>", styles["Normal"])
    )

    story.append(
        Paragraph(f"<b>{title}</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(content, styles["BodyText"])
    )

    doc.build(story)

    return filename